<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>$(MSBuildProjectName)-lib</AssemblyName>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Authors>Xslash</Authors>
    <Description>An unofficial 7TV API library for C#</Description>
    <Version>1.2.5</Version>
    <PackageProjectUrl>https://github.com/Xslash58/SevenTV-lib</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Xslash58/SevenTV-lib</RepositoryUrl>
    <PackageTags>7tv;v3</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>
